# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gk < Formula
  desc "A simple CLI to submit changes"
  homepage "https://github.com/martinbernstorff/gokid"
  version "1.28.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MartinBernstorff/gokid/releases/download/v1.28.2/gk_Darwin_x86_64.tar.gz"
      sha256 "c73aa4e8d27a848944d8ee5ec093f0aa83339abc1599960e256a127d84a4b339"

      def install
        bin.install "gk"
        bin.install_symlink bin/"gk" => "gokid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MartinBernstorff/gokid/releases/download/v1.28.2/gk_Darwin_arm64.tar.gz"
      sha256 "ff473007a7ddcae4400c6991383c1c97e2132455b08930d37f3a9067f8108d48"

      def install
        bin.install "gk"
        bin.install_symlink bin/"gk" => "gokid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MartinBernstorff/gokid/releases/download/v1.28.2/gk_Linux_x86_64.tar.gz"
        sha256 "ab421bab15acbbbfdd0650af3e44eb03e6485ac63246e7ff331bb97606971c6d"

        def install
          bin.install "gk"
          bin.install_symlink bin/"gk" => "gokid"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MartinBernstorff/gokid/releases/download/v1.28.2/gk_Linux_arm64.tar.gz"
        sha256 "331d3388922b3cf2174c3c042ddcc46356e37c21fc61f3d50ff8c87c42d9c265"

        def install
          bin.install "gk"
          bin.install_symlink bin/"gk" => "gokid"
        end
      end
    end
  end
end
