# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gk < Formula
  desc "A simple CLI to submit changes"
  homepage "https://github.com/martinbernstorff/gokid"
  version "1.31.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MartinBernstorff/gokid/releases/download/v1.31.1/gk_Darwin_x86_64.tar.gz"
      sha256 "9344cb2cfa729b2438214990917b919910044e3c4fa7f26d356cff14135101ea"

      def install
        bin.install "gk"
        bin.install_symlink bin/"gk" => "gokid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MartinBernstorff/gokid/releases/download/v1.31.1/gk_Darwin_arm64.tar.gz"
      sha256 "2dcd767f1d3a768d404e341cf990fbe71e4db83dc503bf041451de3fb11e860d"

      def install
        bin.install "gk"
        bin.install_symlink bin/"gk" => "gokid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MartinBernstorff/gokid/releases/download/v1.31.1/gk_Linux_x86_64.tar.gz"
        sha256 "dc885f2c2597399aa9b4e531f065213ed0d85c33bc86618d64979b4ff91db69d"

        def install
          bin.install "gk"
          bin.install_symlink bin/"gk" => "gokid"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MartinBernstorff/gokid/releases/download/v1.31.1/gk_Linux_arm64.tar.gz"
        sha256 "2a69ae42d980498effac24c0add2db0f209ed24636f1a3ae13a56bacef499ac7"

        def install
          bin.install "gk"
          bin.install_symlink bin/"gk" => "gokid"
        end
      end
    end
  end
end
