# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gokid < Formula
  desc "A simple CLI to submit changes"
  homepage "https://github.com/martinbernstorff/gokid"
  version "0.0.0-SNAPSHOT-84dd20f"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/MartinBernstorff/gokid/releases/download/v0.0.0/gokid_Darwin_x86_64.tar.gz"
      sha256 "b3254ab3a719f05ab657e59250876e04b4acbca2067db38568822c1efaf85de1"

      def install
        bin.install "gokid"
      end
    end
    on_arm do
      url "https://github.com/MartinBernstorff/gokid/releases/download/v0.0.0/gokid_Darwin_arm64.tar.gz"
      sha256 "dee9c77c254410d85c944158a698a8d06b091d647b90f2668013040253baf34c"

      def install
        bin.install "gokid"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MartinBernstorff/gokid/releases/download/v0.0.0/gokid_Linux_x86_64.tar.gz"
        sha256 "0dbc4be647ed8ac589d8cdded163db7202533c06ce41f63bf514cfbc2c0c163c"

        def install
          bin.install "gokid"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MartinBernstorff/gokid/releases/download/v0.0.0/gokid_Linux_arm64.tar.gz"
        sha256 "bebefe1a03e384ffee45f5dbf61d248300592a330c40f2be8cc776302bccfcc0"

        def install
          bin.install "gokid"
        end
      end
    end
  end
end
