# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gokid < Formula
  desc "A simple CLI to submit changes"
  homepage "https://github.com/martinbernstorff/gokid"
  version "0.4.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/MartinBernstorff/gokid/releases/download/v0.4.1/gokid_Darwin_x86_64.tar.gz"
      sha256 "b6514fb878196fca88ce5001a2185be59436d759aab85d1439a94e5740a9732d"

      def install
        bin.install "gokid"
      end
    end
    on_arm do
      url "https://github.com/MartinBernstorff/gokid/releases/download/v0.4.1/gokid_Darwin_arm64.tar.gz"
      sha256 "e3aab299444437daa513ddfd0a0dcc94772d1ef06333b1d656bb70532827922d"

      def install
        bin.install "gokid"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MartinBernstorff/gokid/releases/download/v0.4.1/gokid_Linux_x86_64.tar.gz"
        sha256 "6146b00cbb85f2d60b71867f8f6590c9f594437578d7f4a2f7ef358e8ed517cb"

        def install
          bin.install "gokid"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MartinBernstorff/gokid/releases/download/v0.4.1/gokid_Linux_arm64.tar.gz"
        sha256 "3795cf7a503b3760e39babb136d178b241973d14991a6bf3d1f3484e78a65410"

        def install
          bin.install "gokid"
        end
      end
    end
  end
end
