# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gokid < Formula
  desc "A simple CLI to submit changes"
  homepage "https://github.com/martinbernstorff/gokid"
  version "1.0.14"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/MartinBernstorff/gokid/releases/download/v1.0.14/gokid_Darwin_x86_64.tar.gz"
      sha256 "8fd261e9d83f8d7fbc52b19108fcca1be6cfa6e8c9c9bcd15c8bb2c15273ac5f"

      def install
        bin.install "gokid"
      end
    end
    on_arm do
      url "https://github.com/MartinBernstorff/gokid/releases/download/v1.0.14/gokid_Darwin_arm64.tar.gz"
      sha256 "a6011142206a13d96af4095130ef05df9c39746b24b5267e210012ef42475bda"

      def install
        bin.install "gokid"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MartinBernstorff/gokid/releases/download/v1.0.14/gokid_Linux_x86_64.tar.gz"
        sha256 "a8b947bcefa7c518b2805a99771bda284849b08ccafb9018d15942eb69307498"

        def install
          bin.install "gokid"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MartinBernstorff/gokid/releases/download/v1.0.14/gokid_Linux_arm64.tar.gz"
        sha256 "23e6c41bdc739abe631fa651938d7e75ea02aa0663c1da9a145d2ba9a5921962"

        def install
          bin.install "gokid"
        end
      end
    end
  end
end
